### ISSUE TITLE
Conversion bugs meta issue

### ISSUE THREAD

**Issue by glennsl** [reasonml/reason-tools#65]
The purpose of this issue is to provide a better overview of conversion issues, and to provide test cases, both current and historic to prevent regressions.

### Should be converted
- [ ] https://bucklescript.github.io/bucklescript/api/Js_re.html (#47)
- [ ] https://realworldocaml.org/ (#15)
- [ ] https://bucklescript.github.io/bucklescript/api/Js.Global.html (#77)

### Should not be converted
- [ ] http://asciidoctor.org/docs/user-manual/ (#40, blacklisted)
- [ ] http://nim-lang.org/index.html (#21)
- [ ] https://caml.inria.fr/pub/docs/u3-ocaml/ocaml-objects.html (#17, blacklisted)
- [ ] https://www.mercurial-scm.org/wiki/MergeDriverPlan

### Incorrect formatting/styling
- [ ] https://mwhittaker.github.io/distributed-systems-ocaml/code_MorePipes.html (#49, no-pre, blacklisted)
- [ ] https://ocaml.janestreet.com/ocaml-core/latest/doc/core/ (#46, blacklisted)
- [ ] https://ocaml.janestreet.com/ocaml-core/latest/doc/core/Std/Option.mod/ (#27, odoc)
- [ ] http://ounit.forge.ocamlcore.org/api-ounit/index.html (#26, no-pre)
- [ ] ocamldoc link preservation (#11)
- [ ] https://bucklescript.github.io/bucklescript/api/Js.Global.html (#77)

### Fails refmt
- [x] http://ounit.forge.ocamlcore.org/api-ounit/ (#42)
- [x] https://caml.inria.fr/pub/docs/u3-ocaml/ocaml051.html (#23)
